@author:zach
@owner:zach

Feature: QR Code

  Background: sqm-qr-code is in the widget HTML
    Given "sqm-qr-code" is in the widget's html template

  @motivating
  Scenario: Including sqm-qr-code in widget html displays the QR code component
    Given "sqm-qr-code" is in the widget's html template
    When the widget loads
    And a QR code loads successfully
    Then the QR code component is displayed
    And it has "Share your QR code" text
    And it has a "View QR code" primary button
    And it has a "Download" text button
    And it has a "Print" text button

  @motivating
  Scenario: The QR code is displayed when the button is clicked
    Given a QR code loads successfully
    When a user clicks the "View QR code" button
    Then a dialog is shown
    And the dialog contains the following
      | components      |
      | QR code         |
      | download button |
      | print button    |
      | close button    |
    And the dialog has header "Share your QR code"
    And the QR code is 300x300 pixels
    And the QR code is in "svg" format

  @motivating
  Scenario Outline: No engagement event is fired
    Given a QR code loads successfully
    When the user <action>
    Then a "USER_REFERRAL_PROGRAM_ENGAGEMENT_EVENT" event is fired
    And the event has meta
      """
      {
      engagementMedium: <POPUP or EMBED>,
      shareMedium: DIRECT
      }
      """
    Examples:
      | action            |
      | clicks "Download" |
      | clicks "Print"    |

  @minutia
  Scenario: No load event is fired if they download the QR code via right click menu
    Given a QR code is viewed
    And it loads successfully
    When the user right clicks the QR code
    And clicks "Save image"
    Then no engagement event is fired

  @motivating
  Scenario Outline: The QR code redirects to the correct URL
    Given a QR code loads successfully
    And a QR code is generated by <method>
    When a user scans the QR code
    Then they are redirected via the associated share link

  @motivating
  Scenario: The QR code is downloadable
    Given a QR code loads successfully
    When a user clicks "Download"
    Then the QR code is fetched
    And the fetched QR code has format "png"
    And the fetched QR code has size 500x500 pixels
    When the QR is fetched successfully
    Then the file download starts

  @motivating
  Scenario: The QR code is printable
    Given a QR code loads successfully
    When a user clicks "Download"
    Then the QR code is fetched
    And the fetched QR code has format "png"
    And the fetched QR code has size 800x800 pixels
    And has redundancy set to "High" (or "H")
    When the QR is fetched successfully
    Then then a new tab is opened
    And a print dialog is displayed showing a document with the QR code
    When the document is printed or a user cancels
    Then the tab closes automatically

  @minutia
  Scenario Outline: Error states when the QR code can't be loaded
    Given an error when <asyncAction>
    Then a banner is shown above the QR code component
    And the banner has the following text
      """
      TODO
      """
    Examples:
      | asyncAction                            |
      | the sharelink request fails            |
      | the view QR code request fails         |
      | the downloadable QR code request fails |
      | the printable QR code request fails    |


