/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SqmBigStat {
        "type": string;
    }
    interface SqmLeaderboard {
        "statsheading": string;
        "usersheading": string;
    }
    interface SqmLeaderboardRank {
        "rank"?: string;
    }
    interface SqmReferralList {
        "downloadedtext": string;
        "downloadedunqualifiedtext": string;
        "newreferraltext": string;
        "noreferralsyet": string;
        "paginateless": string;
        "paginatemore": string;
        "pickrewardtext": string;
        "purchasedeligibletext": string;
        "purchasednoteligibletext": string;
        "rewardpendingtext": string;
        "rewardredeemedtext": string;
        "rewardsavailabletext": string;
        "showStatus": boolean;
        "titleText": string;
        "unknownuser": string;
    }
    interface SqmShareButton {
        "disabled"?: boolean;
        "hideicon"?: boolean;
        "iconslot"?: 'prefix' | 'suffix';
        /**
          * Which medium sharing should occur on
         */
        "medium": 'facebook' | 'twitter' | 'email' | 'TODO';
        "pill"?: boolean;
        /**
          * Optional programId, or uses the programId context where this button is rendered.
         */
        "programId"?: string;
        "size"?: 'small' | 'medium' | 'large';
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'default' | 'text';
    }
    interface SqmShareLink {
        "disabled"?: boolean;
        "icon"?: string;
        "iconlabel"?: string;
        "sharelink"?: string;
        "tooltiptext"?: string;
    }
    interface SqmStencilbook {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSqmBigStatElement extends Components.SqmBigStat, HTMLStencilElement {
    }
    var HTMLSqmBigStatElement: {
        prototype: HTMLSqmBigStatElement;
        new (): HTMLSqmBigStatElement;
    };
    interface HTMLSqmLeaderboardElement extends Components.SqmLeaderboard, HTMLStencilElement {
    }
    var HTMLSqmLeaderboardElement: {
        prototype: HTMLSqmLeaderboardElement;
        new (): HTMLSqmLeaderboardElement;
    };
    interface HTMLSqmLeaderboardRankElement extends Components.SqmLeaderboardRank, HTMLStencilElement {
    }
    var HTMLSqmLeaderboardRankElement: {
        prototype: HTMLSqmLeaderboardRankElement;
        new (): HTMLSqmLeaderboardRankElement;
    };
    interface HTMLSqmReferralListElement extends Components.SqmReferralList, HTMLStencilElement {
    }
    var HTMLSqmReferralListElement: {
        prototype: HTMLSqmReferralListElement;
        new (): HTMLSqmReferralListElement;
    };
    interface HTMLSqmShareButtonElement extends Components.SqmShareButton, HTMLStencilElement {
    }
    var HTMLSqmShareButtonElement: {
        prototype: HTMLSqmShareButtonElement;
        new (): HTMLSqmShareButtonElement;
    };
    interface HTMLSqmShareLinkElement extends Components.SqmShareLink, HTMLStencilElement {
    }
    var HTMLSqmShareLinkElement: {
        prototype: HTMLSqmShareLinkElement;
        new (): HTMLSqmShareLinkElement;
    };
    interface HTMLSqmStencilbookElement extends Components.SqmStencilbook, HTMLStencilElement {
    }
    var HTMLSqmStencilbookElement: {
        prototype: HTMLSqmStencilbookElement;
        new (): HTMLSqmStencilbookElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sqm-big-stat": HTMLSqmBigStatElement;
        "sqm-leaderboard": HTMLSqmLeaderboardElement;
        "sqm-leaderboard-rank": HTMLSqmLeaderboardRankElement;
        "sqm-referral-list": HTMLSqmReferralListElement;
        "sqm-share-button": HTMLSqmShareButtonElement;
        "sqm-share-link": HTMLSqmShareLinkElement;
        "sqm-stencilbook": HTMLSqmStencilbookElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SqmBigStat {
        "type"?: string;
    }
    interface SqmLeaderboard {
        "statsheading"?: string;
        "usersheading"?: string;
    }
    interface SqmLeaderboardRank {
        "rank"?: string;
    }
    interface SqmReferralList {
        "downloadedtext"?: string;
        "downloadedunqualifiedtext"?: string;
        "newreferraltext"?: string;
        "noreferralsyet"?: string;
        "paginateless"?: string;
        "paginatemore"?: string;
        "pickrewardtext"?: string;
        "purchasedeligibletext"?: string;
        "purchasednoteligibletext"?: string;
        "rewardpendingtext"?: string;
        "rewardredeemedtext"?: string;
        "rewardsavailabletext"?: string;
        "showStatus"?: boolean;
        "titleText"?: string;
        "unknownuser"?: string;
    }
    interface SqmShareButton {
        "disabled"?: boolean;
        "hideicon"?: boolean;
        "iconslot"?: 'prefix' | 'suffix';
        /**
          * Which medium sharing should occur on
         */
        "medium"?: 'facebook' | 'twitter' | 'email' | 'TODO';
        "pill"?: boolean;
        /**
          * Optional programId, or uses the programId context where this button is rendered.
         */
        "programId"?: string;
        "size"?: 'small' | 'medium' | 'large';
        "type"?: 'primary' | 'success' | 'info' | 'warning' | 'danger' | 'default' | 'text';
    }
    interface SqmShareLink {
        "disabled"?: boolean;
        "icon"?: string;
        "iconlabel"?: string;
        "sharelink"?: string;
        "tooltiptext"?: string;
    }
    interface SqmStencilbook {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sqm-big-stat": SqmBigStat;
        "sqm-leaderboard": SqmLeaderboard;
        "sqm-leaderboard-rank": SqmLeaderboardRank;
        "sqm-referral-list": SqmReferralList;
        "sqm-share-button": SqmShareButton;
        "sqm-share-link": SqmShareLink;
        "sqm-stencilbook": SqmStencilbook;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sqm-big-stat": LocalJSX.SqmBigStat & JSXBase.HTMLAttributes<HTMLSqmBigStatElement>;
            "sqm-leaderboard": LocalJSX.SqmLeaderboard & JSXBase.HTMLAttributes<HTMLSqmLeaderboardElement>;
            "sqm-leaderboard-rank": LocalJSX.SqmLeaderboardRank & JSXBase.HTMLAttributes<HTMLSqmLeaderboardRankElement>;
            "sqm-referral-list": LocalJSX.SqmReferralList & JSXBase.HTMLAttributes<HTMLSqmReferralListElement>;
            "sqm-share-button": LocalJSX.SqmShareButton & JSXBase.HTMLAttributes<HTMLSqmShareButtonElement>;
            "sqm-share-link": LocalJSX.SqmShareLink & JSXBase.HTMLAttributes<HTMLSqmShareLinkElement>;
            "sqm-stencilbook": LocalJSX.SqmStencilbook & JSXBase.HTMLAttributes<HTMLSqmStencilbookElement>;
        }
    }
}
