export default {
  totalCount: 53,
  count: 4,
  data: [
    {
      id: "61f7878e096c9265de88b46f",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643612046293,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f7878e096c9265de88b414",
        creditRedeemed: 50,
        prettyRedeemedCredit: "50 Points",
        unit: "POINT",
        dateRedeemed: 1643612046258,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
    {
      id: "61f449ca096c9265de847ef5",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643399626845,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f449ca096c9265de847ecf",
        creditRedeemed: 50,
        prettyRedeemedCredit: "50 Points",
        unit: "POINT",
        dateRedeemed: 1643399626808,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
    {
      id: "61f43c3d40b8d244bb05dc51",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643396157092,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f43c3d40b8d244bb05dbfa",
        creditRedeemed: 25,
        prettyRedeemedCredit: "25 Points",
        unit: "POINT",
        dateRedeemed: 1643396157045,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
    {
      id: "61f43b4a40b8d244bb05cfe4",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643395914220,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f43b4a40b8d244bb05cf8c",
        creditRedeemed: 25,
        prettyRedeemedCredit: "25 Points",
        unit: "POINT",
        dateRedeemed: 1643395914151,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
    {
      id: "61f43b4a40b8d244bb05cfe4",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643395914220,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f43b4a40b8d244bb05cf8c",
        creditRedeemed: 25,
        prettyRedeemedCredit: "25 Points",
        unit: "POINT",
        dateRedeemed: 1643395914151,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
    {
      id: "61f43b4a40b8d244bb05cfe4",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643395914220,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f43b4a40b8d244bb05cf8c",
        creditRedeemed: 25,
        prettyRedeemedCredit: "25 Points",
        unit: "POINT",
        dateRedeemed: 1643395914151,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
    {
      id: "61f43b4a40b8d244bb05cfe4",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643395914220,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f43b4a40b8d244bb05cf8c",
        creditRedeemed: 25,
        prettyRedeemedCredit: "25 Points",
        unit: "POINT",
        dateRedeemed: 1643395914151,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
    {
      id: "61f43b4a40b8d244bb05cfe4",
      type: "CREDIT",
      value: 1,
      unit: "THING",
      name: null,
      dateGiven: 1643395914220,
      dateExpires: null,
      dateCancelled: null,
      dateRedeemed: null,
      dateScheduledFor: null,
      fuelTankCode: null,
      fuelTankType: null,
      currency: null,
      prettyValue: "1 THING",
      prettyValueNumber: "1",
      prettyAvailableNumber: "1",
      prettyRedeemedNumber: "0",
      programId: null,
      program: null,
      statuses: ["AVAILABLE"],
      pendingReasons: [],
      globalRewardKey: null,
      programRewardKey: null,
      rewardSource: "MANUAL",
      prettyRedeemedCredit: "0 THING",
      prettyAssignedCredit: "1 THING",
      prettyAvailableValue: "1 THING",
      exchangedRewardRedemptionTransaction: {
        id: "61f43b4a40b8d244bb05cf8c",
        creditRedeemed: 25,
        prettyRedeemedCredit: "25 Points",
        unit: "POINT",
        dateRedeemed: 1643395914151,
      },
      referral: null,
      rewardRedemptionTransactions: {
        data: [],
      },
    },
  ],
};
