/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SqbConditionalSection {
        /**
          * Only show this section when a user meets the following conditions.  Can use `user.segments` and `user.customFields`.   - `"VIP" in user.segments`  - `user.customFields.age > 19`
          * @uiName Condition
         */
        "condition": string;
    }
    interface SqbProgramSection {
        /**
          * The program that everything in this section should use
          * @uiName Program
         */
        "programId": string;
    }
}
declare global {
    interface HTMLSqbConditionalSectionElement extends Components.SqbConditionalSection, HTMLStencilElement {
    }
    var HTMLSqbConditionalSectionElement: {
        prototype: HTMLSqbConditionalSectionElement;
        new (): HTMLSqbConditionalSectionElement;
    };
    interface HTMLSqbProgramSectionElement extends Components.SqbProgramSection, HTMLStencilElement {
    }
    var HTMLSqbProgramSectionElement: {
        prototype: HTMLSqbProgramSectionElement;
        new (): HTMLSqbProgramSectionElement;
    };
    interface HTMLElementTagNameMap {
        "sqb-conditional-section": HTMLSqbConditionalSectionElement;
        "sqb-program-section": HTMLSqbProgramSectionElement;
    }
}
declare namespace LocalJSX {
    interface SqbConditionalSection {
        /**
          * Only show this section when a user meets the following conditions.  Can use `user.segments` and `user.customFields`.   - `"VIP" in user.segments`  - `user.customFields.age > 19`
          * @uiName Condition
         */
        "condition"?: string;
    }
    interface SqbProgramSection {
        /**
          * The program that everything in this section should use
          * @uiName Program
         */
        "programId"?: string;
    }
    interface IntrinsicElements {
        "sqb-conditional-section": SqbConditionalSection;
        "sqb-program-section": SqbProgramSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sqb-conditional-section": LocalJSX.SqbConditionalSection & JSXBase.HTMLAttributes<HTMLSqbConditionalSectionElement>;
            "sqb-program-section": LocalJSX.SqbProgramSection & JSXBase.HTMLAttributes<HTMLSqbProgramSectionElement>;
        }
    }
}
