/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SqCode {
    'copied': boolean;
    'open': boolean;
    'syntax': string;
    'tabname': string;
  }
  interface SqCodeExample {}
  interface SqDocs {}
}

declare global {


  interface HTMLSqCodeElement extends Components.SqCode, HTMLStencilElement {}
  var HTMLSqCodeElement: {
    prototype: HTMLSqCodeElement;
    new (): HTMLSqCodeElement;
  };

  interface HTMLSqCodeExampleElement extends Components.SqCodeExample, HTMLStencilElement {}
  var HTMLSqCodeExampleElement: {
    prototype: HTMLSqCodeExampleElement;
    new (): HTMLSqCodeExampleElement;
  };

  interface HTMLSqDocsElement extends Components.SqDocs, HTMLStencilElement {}
  var HTMLSqDocsElement: {
    prototype: HTMLSqDocsElement;
    new (): HTMLSqDocsElement;
  };
  interface HTMLElementTagNameMap {
    'sq-code': HTMLSqCodeElement;
    'sq-code-example': HTMLSqCodeExampleElement;
    'sq-docs': HTMLSqDocsElement;
  }
}

declare namespace LocalJSX {
  interface SqCode extends JSXBase.HTMLAttributes<HTMLSqCodeElement> {
    'copied'?: boolean;
    'open'?: boolean;
    'syntax'?: string;
    'tabname'?: string;
  }
  interface SqCodeExample extends JSXBase.HTMLAttributes<HTMLSqCodeExampleElement> {}
  interface SqDocs extends JSXBase.HTMLAttributes<HTMLSqDocsElement> {}

  interface IntrinsicElements {
    'sq-code': SqCode;
    'sq-code-example': SqCodeExample;
    'sq-docs': SqDocs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


