export default {
  totalCount: 6,
  count: 4,
  referredByReferral: {
    dateConverted: null,
    dateReferralStarted: 1643912659850,
    referrerUser: {
      firstName: "John",
      lastName: "Snow",
      rewards: [],
    },
  },
  data: [
    {
      id: "5cae6b0fcc540e209db45b53",
      referredUser: {
        id: "5cae6b0ce4b0d81c67b78e82",
        accountId: "SPX1MZBIPTFL3E1H",
        firstName: "Aaron",
        lastName: "Hernandez",
        email: "aaronhernandez.uexwltgh@mailosaur.io",
        programGoals: [],
      },
      shareLinkUsed: null,
      referralCodeUsed: "JIMBONEUTRON2",
      moderationStatus: "PENDING",
      dateConverted: 1554934550726,
      dateFraudChecksCompleted: null,
      dateModerated: 1558730033306,
      dateModified: 1554934543447,
      dateReferralEnded: null,
      dateReferralPaid: null,
      dateReferralStarted: 1554934543447,
      dateUserModified: null,
      programId: "sam-partner-test-2",
      program: {
        id: "sam-partner-test-2",
        name: "Partner Program 2.0",
      },
      rewards: [
        {
          id: "5cae6b16cc540e209db45cfa",
          type: "CREDIT",
          value: 1,
          unit: "POINT",
          name: "Partner Reward",
          dateGiven: 1554934550726,
          dateExpires: null,
          dateCancelled: null,
          dateRedeemed: 1637004373582,
          dateScheduledFor: null,
          fuelTankCode: null,
          fuelTankType: null,
          currency: null,
          prettyValue: "1 Point",
          statuses: ["REDEEMED"],
          globalRewardKey: null,
          programRewardKey: "partnerReward",
          rewardRedemptionTransactions: {
            data: [
              {
                exchangedRewards: {
                  data: [
                    {
                      prettyValue: "CAD10.00 Visa* Prepaid Card CAD",
                      type: "INTEGRATION",
                      fuelTankCode: null,
                      globalRewardKey: "gc1",
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
      childNodes: {
        data: [
          {
            data: {
              id: "5cae6b16cc540e209db45cb3",
              statuses: ["AVAILABLE"],
              type: "PCT_DISCOUNT",
              value: 50,
            },
            depth: 1,
          },
          {
            data: {
              id: "5cae6b16cc540e209db45cfa",
              statuses: ["REDEEMED"],
              type: "CREDIT",
              value: 1,
            },
            depth: 1,
          },
        ],
      },
    },
    {
      id: "5cae6a92cc540e209db45106",
      referredUser: {
        id: "5cae6a8fe4b0d81c67b78e60",
        accountId: "B5DY96TJ2HFF321L",
        firstName: "Brian",
        lastName: "Mendez",
        email: "brianmendez.uexwltgh@mailosaur.io",
        programGoals: [],
      },
      shareLinkUsed: null,
      referralCodeUsed: "JIMBONEUTRON2",
      moderationStatus: "PENDING",
      dateConverted: 1554934455495,
      dateFraudChecksCompleted: null,
      dateModerated: 1558730033311,
      dateModified: 1554934418374,
      dateReferralEnded: null,
      dateReferralPaid: null,
      dateReferralStarted: 1554934418374,
      dateUserModified: null,
      programId: "sam-partner-test-2",
      program: {
        id: "sam-partner-test-2",
        name: "Partner Program 2.0",
      },
      rewards: [
        {
          id: "5cae6ab7cc540e209db456cc",
          type: "CREDIT",
          value: 1,
          unit: "POINT",
          name: "Partner Reward",
          dateGiven: 1554934455495,
          dateExpires: null,
          dateCancelled: null,
          dateRedeemed: 1637004373582,
          dateScheduledFor: null,
          fuelTankCode: null,
          fuelTankType: null,
          currency: null,
          prettyValue: "1 Point",
          statuses: ["REDEEMED"],
          globalRewardKey: null,
          programRewardKey: "partnerReward",
          rewardRedemptionTransactions: {
            data: [
              {
                exchangedRewards: {
                  data: [
                    {
                      prettyValue: "CAD10.00 Visa* Prepaid Card CAD",
                      type: "INTEGRATION",
                      fuelTankCode: null,
                      globalRewardKey: "gc1",
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
      childNodes: {
        data: [
          {
            data: {
              id: "5cae6ab7cc540e209db456cc",
              statuses: ["REDEEMED"],
              type: "CREDIT",
              value: 1,
            },
            depth: 1,
          },
          {
            data: {
              id: "5cae6a92cc540e209db45136",
              statuses: ["AVAILABLE"],
              type: "PCT_DISCOUNT",
              value: 50,
            },
            depth: 1,
          },
        ],
      },
    },
    {
      id: "5cae6a42cc540e209db44b5a",
      referredUser: {
        id: "5cae6a40e4b0d81c67b78e3e",
        accountId: "3TW6KPEDCKIMUMPS",
        firstName: "Loretta",
        lastName: "Harper",
        email: "lorettaharper.uexwltgh@mailosaur.io",
        programGoals: [],
      },
      shareLinkUsed: null,
      referralCodeUsed: "JIMBONEUTRON2",
      moderationStatus: "PENDING",
      dateConverted: 1554934342984,
      dateFraudChecksCompleted: null,
      dateModerated: 1558730033315,
      dateModified: 1554934338318,
      dateReferralEnded: null,
      dateReferralPaid: null,
      dateReferralStarted: 1554934338318,
      dateUserModified: null,
      programId: "sam-partner-test-2",
      program: {
        id: "sam-partner-test-2",
        name: "Partner Program 2.0",
      },
      rewards: [
        {
          id: "5cae6a46cc540e209db44cf2",
          type: "CREDIT",
          value: 1,
          unit: "POINT",
          name: "Partner Reward",
          dateGiven: 1554934342984,
          dateExpires: null,
          dateCancelled: null,
          dateRedeemed: 1637004373582,
          dateScheduledFor: null,
          fuelTankCode: null,
          fuelTankType: null,
          currency: null,
          prettyValue: "1 Point",
          statuses: ["REDEEMED"],
          globalRewardKey: null,
          programRewardKey: "partnerReward",
          rewardRedemptionTransactions: {
            data: [
              {
                exchangedRewards: {
                  data: [
                    {
                      prettyValue: "CAD10.00 Visa* Prepaid Card CAD",
                      type: "INTEGRATION",
                      fuelTankCode: null,
                      globalRewardKey: "gc1",
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
      childNodes: {
        data: [
          {
            data: {
              id: "5cae6a42cc540e209db44b7e",
              statuses: ["AVAILABLE"],
              type: "PCT_DISCOUNT",
              value: 50,
            },
            depth: 1,
          },
          {
            data: {
              id: "5cae6a46cc540e209db44cf2",
              statuses: ["REDEEMED"],
              type: "CREDIT",
              value: 1,
            },
            depth: 1,
          },
        ],
      },
    },
    {
      id: "5cae6a37cc540e209db44937",
      referredUser: {
        id: "5cae6a33e4b0d81c67b78e1e",
        accountId: "41E0PY65021C3T5Z",
        firstName: "Isaac",
        lastName: "Meyer",
        email: "isaacmeyer.uexwltgh@mailosaur.io",
        programGoals: [],
      },
      shareLinkUsed: null,
      referralCodeUsed: "JIMBONEUTRON2",
      moderationStatus: "PENDING",
      dateConverted: null,
      dateFraudChecksCompleted: null,
      dateModerated: 1554934327291,
      dateModified: 1554934327291,
      dateReferralEnded: null,
      dateReferralPaid: null,
      dateReferralStarted: 1554934327291,
      dateUserModified: null,
      programId: "sam-partner-test-2",
      program: {
        id: "sam-partner-test-2",
        name: "Partner Program 2.0",
      },
      rewards: [],
      childNodes: {
        data: [
          {
            data: {
              id: "5cae6a37cc540e209db44954",
              statuses: ["AVAILABLE"],
              type: "PCT_DISCOUNT",
              value: 50,
            },
            depth: 1,
          },
        ],
      },
    },
    {
      id: "5cae6a37cc540e209db44937",
      referredUser: {
        id: "5cae6a33e4b0d81c67b78e1e",
        accountId: "41E0PY65021C3T5Z",
        firstName: "Joe",
        lastName: "Schmoe",
        email: "joeschmoe.uexwltgh@mailosaur.io",
        programGoals: [],
      },
      shareLinkUsed: null,
      referralCodeUsed: "JIMBONEUTRON2",
      moderationStatus: "PENDING",
      dateConverted: null,
      dateFraudChecksCompleted: null,
      dateModerated: 1554934327291,
      dateModified: 1554934327291,
      dateReferralEnded: null,
      dateReferralPaid: null,
      dateReferralStarted: 1554934327291,
      dateUserModified: null,
      programId: "sam-partner-test-2",
      program: {
        id: "sam-partner-test-2",
        name: "Partner Program 2.0",
      },
      rewards: [],
      childNodes: {
        data: [
          {
            data: {
              id: "5cae6a37cc540e209db44954",
              statuses: ["AVAILABLE"],
              type: "PCT_DISCOUNT",
              value: 50,
            },
            depth: 1,
          },
        ],
      },
    },
    {
      id: "5cae6a37cc540e209db44937",
      referredUser: {
        id: "5cae6a33e4b0d81c67b78e1e",
        accountId: "41E0PY65021C3T5Z",
        firstName: "John",
        lastName: "Smith",
        email: "johnsmith.uexwltgh@mailosaur.io",
        programGoals: [],
      },
      shareLinkUsed: null,
      referralCodeUsed: "JIMBONEUTRON2",
      moderationStatus: "PENDING",
      dateConverted: null,
      dateFraudChecksCompleted: null,
      dateModerated: 1554934327291,
      dateModified: 1554934327291,
      dateReferralEnded: null,
      dateReferralPaid: null,
      dateReferralStarted: 1554934327291,
      dateUserModified: null,
      programId: "sam-partner-test-2",
      program: {
        id: "sam-partner-test-2",
        name: "Partner Program 2.0",
      },
      rewards: [],
      childNodes: {
        data: [
          {
            data: {
              id: "5cae6a37cc540e209db44954",
              statuses: ["AVAILABLE"],
              type: "PCT_DISCOUNT",
              value: 50,
            },
            depth: 1,
          },
        ],
      },
    },
    {
      id: "5cae6a37cc540e209db44937",
      referredUser: {
        id: "5cae6a33e4b0d81c67b78e1e",
        accountId: "41E0PY65021C3T5Z",
        firstName: "Charleston",
        lastName: "Chew",
        email: "charlestonchew.uexwltgh@mailosaur.io",
        programGoals: [],
      },
      shareLinkUsed: null,
      referralCodeUsed: "JIMBONEUTRON2",
      moderationStatus: "PENDING",
      dateConverted: 1554934550726,
      dateFraudChecksCompleted: null,
      dateModerated: 1554934327291,
      dateModified: 1554934327291,
      dateReferralEnded: null,
      dateReferralPaid: null,
      dateReferralStarted: 1554934327291,
      dateUserModified: null,
      programId: "sam-partner-test-2",
      program: {
        id: "sam-partner-test-2",
        name: "Partner Program 2.0",
      },
      rewards: [],
      childNodes: {
        data: [
          {
            data: {
              id: "5cae6a37cc540e209db44954",
              statuses: ["AVAILABLE"],
              type: "PCT_DISCOUNT",
              value: 50,
            },
            depth: 1,
          },
        ],
      },
    },
  ],
};
