export const INDIRECT_TAX_COUNTRIES = [
  { countryCode: "GB", displayName: "United Kingdom" },
  { countryCode: "AT", displayName: "Austria" },
  { countryCode: "BE", displayName: "Belgium" },
  { countryCode: "BG", displayName: "Bulgaria" },
  { countryCode: "CA", displayName: "Canada" },
  { countryCode: "HR", displayName: "Croatia" },
  { countryCode: "CY", displayName: "Cyprus" },
  { countryCode: "CZ", displayName: "Czechia" },
  { countryCode: "DK", displayName: "Denmark" },
  { countryCode: "EE", displayName: "Estonia" },
  { countryCode: "FI", displayName: "Finland" },
  { countryCode: "FR", displayName: "France" },
  { countryCode: "DE", displayName: "Germany" },
  { countryCode: "GR", displayName: "Greece" },
  { countryCode: "HU", displayName: "Hungary" },
  { countryCode: "IS", displayName: "Iceland" },
  { countryCode: "IL", displayName: "Israel" },
  { countryCode: "IE", displayName: "Ireland" },
  { countryCode: "IT", displayName: "Italy" },
  { countryCode: "LV", displayName: "Latvia" },
  { countryCode: "LT", displayName: "Lithuania" },
  { countryCode: "LU", displayName: "Luxembourg" },
  { countryCode: "MT", displayName: "Malta" },
  { countryCode: "MX", displayName: "Mexico" },
  { countryCode: "NL", displayName: "Netherlands" },
  { countryCode: "NO", displayName: "Norway" },
  { countryCode: "PH", displayName: "Philippines" },
  { countryCode: "PL", displayName: "Poland" },
  { countryCode: "PT", displayName: "Portugal" },
  { countryCode: "RO", displayName: "Romania" },
  { countryCode: "RU", displayName: "Russia" },
  { countryCode: "SK", displayName: "Slovakia" },
  { countryCode: "SI", displayName: "Slovenia" },
  { countryCode: "ES", displayName: "Spain" },
  { countryCode: "SE", displayName: "Sweden" },
  { countryCode: "ZA", displayName: "South Africa" },
  { countryCode: "KR", displayName: "South Korea" },
  { countryCode: "CH", displayName: "Switzerland" },
  { countryCode: "TW", displayName: "Taiwan" },
  { countryCode: "TH", displayName: "Thailand" },
  { countryCode: "TR", displayName: "Turkey" },
  { countryCode: "AE", displayName: "United Arab Emirates" },
];
