import { TaxCountry } from "./sqm-tax-and-cash/data";

export const INDIRECT_TAX_COUNTRIES = [
  {
    countryCode: "GB",
    impactCountryCode: "GB",
    taxType: "GST",
    displayName: "United Kingdom",
  },
  {
    countryCode: "AT",
    impactCountryCode: "AT",
    taxType: "GST",
    displayName: "Austria",
  },
  {
    countryCode: "BE",
    impactCountryCode: "BE",
    taxType: "GST",
    displayName: "Belgium",
  },
  {
    countryCode: "BG",
    impactCountryCode: "BG",
    taxType: "GST",
    displayName: "Bulgaria",
  },
  {
    countryCode: "CA",
    impactCountryCode: "CA",
    taxType: "HST",
    displayName: "Canada",
  },
  {
    countryCode: "HR",
    impactCountryCode: "HR",
    taxType: "GST",
    displayName: "Croatia",
  },
  {
    countryCode: "CY",
    impactCountryCode: "CY",
    taxType: "GST",
    displayName: "Cyprus",
  },
  {
    countryCode: "CZ",
    impactCountryCode: "CZ",
    taxType: "GST",
    displayName: "Czechia",
  },
  {
    countryCode: "DK",
    impactCountryCode: "DK",
    taxType: "GST",
    displayName: "Denmark",
  },
  {
    countryCode: "EE",
    impactCountryCode: "EE",
    taxType: "GST",
    displayName: "Estonia",
  },
  {
    countryCode: "FI",
    impactCountryCode: "FI",
    taxType: "GST",
    displayName: "Finland",
  },
  {
    countryCode: "FR",
    impactCountryCode: "FR",
    taxType: "GST",
    displayName: "France",
  },
  {
    countryCode: "DE",
    impactCountryCode: "DE",
    taxType: "GST",
    displayName: "Germany",
  },
  {
    countryCode: "GR",
    impactCountryCode: "GR",
    taxType: "GST",
    displayName: "Greece",
  },
  {
    countryCode: "HU",
    impactCountryCode: "HU",
    taxType: "GST",
    displayName: "Hungary",
  },
  {
    countryCode: "IS",
    impactCountryCode: "IS",
    taxType: "GST",
    displayName: "Iceland",
  },
  {
    countryCode: "IL",
    impactCountryCode: "IL",
    taxType: "GST",
    displayName: "Israel",
  },
  {
    countryCode: "IE",
    impactCountryCode: "IE",
    taxType: "GST",
    displayName: "Ireland",
  },
  {
    countryCode: "IT",
    impactCountryCode: "IT",
    taxType: "GST",
    displayName: "Italy",
  },
  {
    countryCode: "LV",
    impactCountryCode: "LV",
    taxType: "GST",
    displayName: "Latvia",
  },
  {
    countryCode: "LT",
    impactCountryCode: "LT",
    taxType: "GST",
    displayName: "Lithuania",
  },
  {
    countryCode: "LU",
    impactCountryCode: "LU",
    taxType: "GST",
    displayName: "Luxembourg",
  },
  {
    countryCode: "MT",
    impactCountryCode: "MT",
    taxType: "GST",
    displayName: "Malta",
  },
  {
    countryCode: "MX",
    impactCountryCode: "MX",
    taxType: "GST",
    displayName: "Mexico",
  },
  {
    countryCode: "NL",
    impactCountryCode: "NL",
    taxType: "GST",
    displayName: "Netherlands",
  },
  {
    countryCode: "NO",
    impactCountryCode: "NO",
    taxType: "GST",
    displayName: "Norway",
  },
  {
    countryCode: "PH",
    impactCountryCode: "PH",
    taxType: "GST",
    displayName: "Philippines",
  },
  {
    countryCode: "PL",
    impactCountryCode: "PL",
    taxType: "GST",
    displayName: "Poland",
  },
  {
    countryCode: "PT",
    impactCountryCode: "PT",
    taxType: "GST",
    displayName: "Portugal",
  },
  {
    countryCode: "RO",
    impactCountryCode: "RO",
    taxType: "GST",
    displayName: "Romania",
  },
  {
    countryCode: "RU",
    impactCountryCode: "RU",
    taxType: "GST",
    displayName: "Russia",
  },
  {
    countryCode: "SK",
    impactCountryCode: "SK",
    taxType: "GST",
    displayName: "Slovakia",
  },
  {
    countryCode: "SI",
    impactCountryCode: "SI",
    taxType: "GST",
    displayName: "Slovenia",
  },
  {
    countryCode: "ES",
    impactCountryCode: "ES",
    taxType: "GST",
    displayName: "Spain",
  },
  {
    countryCode: "SE",
    impactCountryCode: "SE",
    taxType: "GST",
    displayName: "Sweden",
  },
  {
    countryCode: "ZA",
    impactCountryCode: "ZA",
    taxType: "GST",
    displayName: "South Africa",
  },
  {
    countryCode: "KR",
    impactCountryCode: "KR",
    taxType: "GST",
    displayName: "South Korea",
  },
  {
    countryCode: "CH",
    impactCountryCode: "CH",
    taxType: "GST",
    displayName: "Switzerland",
  },
  {
    countryCode: "TW",
    impactCountryCode: "TW",
    taxType: "GST",
    displayName: "Taiwan",
  },
  {
    countryCode: "TH",
    impactCountryCode: "TH",
    taxType: "GST",
    displayName: "Thailand",
  },
  {
    countryCode: "TR",
    impactCountryCode: "TR",
    taxType: "GST",
    displayName: "Turkey",
  },
  {
    countryCode: "AE",
    impactCountryCode: "AE",
    taxType: "GST",
    displayName: "United Arab Emirates",
  },
];
