export const INDIRECT_TAX_COUNTRIES = [
  { countryCode: "GB", taxType: "GST", displayName: "United Kingdom" },
  { countryCode: "AT", taxType: "GST", displayName: "Austria" },
  { countryCode: "BE", taxType: "GST", displayName: "Belgium" },
  { countryCode: "BG", taxType: "GST", displayName: "Bulgaria" },
  { countryCode: "CA", taxType: "HST", displayName: "Canada" },
  { countryCode: "HR", taxType: "GST", displayName: "Croatia" },
  { countryCode: "CY", taxType: "GST", displayName: "Cyprus" },
  { countryCode: "CZ", taxType: "GST", displayName: "Czechia" },
  { countryCode: "DK", taxType: "GST", displayName: "Denmark" },
  { countryCode: "EE", taxType: "GST", displayName: "Estonia" },
  { countryCode: "FI", taxType: "GST", displayName: "Finland" },
  { countryCode: "FR", taxType: "GST", displayName: "France" },
  { countryCode: "DE", taxType: "GST", displayName: "Germany" },
  { countryCode: "GR", taxType: "GST", displayName: "Greece" },
  { countryCode: "HU", taxType: "GST", displayName: "Hungary" },
  { countryCode: "IS", taxType: "GST", displayName: "Iceland" },
  { countryCode: "IL", taxType: "GST", displayName: "Israel" },
  { countryCode: "IE", taxType: "GST", displayName: "Ireland" },
  { countryCode: "IT", taxType: "GST", displayName: "Italy" },
  { countryCode: "LV", taxType: "GST", displayName: "Latvia" },
  { countryCode: "LT", taxType: "GST", displayName: "Lithuania" },
  { countryCode: "LU", taxType: "GST", displayName: "Luxembourg" },
  { countryCode: "MT", taxType: "GST", displayName: "Malta" },
  { countryCode: "MX", taxType: "GST", displayName: "Mexico" },
  { countryCode: "NL", taxType: "GST", displayName: "Netherlands" },
  { countryCode: "NO", taxType: "GST", displayName: "Norway" },
  { countryCode: "PH", taxType: "GST", displayName: "Philippines" },
  { countryCode: "PL", taxType: "GST", displayName: "Poland" },
  { countryCode: "PT", taxType: "GST", displayName: "Portugal" },
  { countryCode: "RO", taxType: "GST", displayName: "Romania" },
  { countryCode: "RU", taxType: "GST", displayName: "Russia" },
  { countryCode: "SK", taxType: "GST", displayName: "Slovakia" },
  { countryCode: "SI", taxType: "GST", displayName: "Slovenia" },
  { countryCode: "ES", taxType: "GST", displayName: "Spain" },
  { countryCode: "SE", taxType: "GST", displayName: "Sweden" },
  { countryCode: "ZA", taxType: "GST", displayName: "South Africa" },
  { countryCode: "KR", taxType: "GST", displayName: "South Korea" },
  { countryCode: "CH", taxType: "GST", displayName: "Switzerland" },
  { countryCode: "TW", taxType: "GST", displayName: "Taiwan" },
  { countryCode: "TH", taxType: "GST", displayName: "Thailand" },
  { countryCode: "TR", taxType: "GST", displayName: "Turkey" },
  { countryCode: "AE", taxType: "GST", displayName: "United Arab Emirates" },
];
