export const INDIRECT_TAX_PROVINCES = [
  { provinceCode: "AB", taxType: "GST", displayName: "Alberta" },
  { provinceCode: "BC", taxType: "GST", displayName: "British Columbia" },
  { provinceCode: "MB", taxType: "GST", displayName: "Manitoba" },
  { provinceCode: "NB", taxType: "HST", displayName: "New Brunswick" },
  { provinceCode: "NL", taxType: "HST", displayName: "Newfoundland" },
  { provinceCode: "NT", taxType: "GST", displayName: "North West Territories" },
  { provinceCode: "NS", taxType: "HST", displayName: "Nova Scotia" },
  { provinceCode: "NU", taxType: "GST", displayName: "Nunavut" },
  { provinceCode: "ON", taxType: "HST", displayName: "Ontario" },
  { provinceCode: "PE", taxType: "HST", displayName: "Prince Edward Island" },
  { provinceCode: "QC", taxType: "GST", displayName: "Quebec" },
  { provinceCode: "SK", taxType: "GST", displayName: "Saskatchewan" },
  { provinceCode: "YT", taxType: "GST", displayName: "Yukon" },
];
