name: Mint Components Release
on:
  workflow_call:

permissions: {}

jobs:
  version:
    runs-on: ubuntu-latest
    name: Version Mint Components

    permissions:
      contents: write # Push commits to edit version numbers/changelogs
      id-token: write # GCP workload identity federation
      pull-requests: write # Open a PR
      issues: read # ??

    defaults:
      run:
        working-directory: packages/mint-components

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # de0fa = v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 53b83 = v6.3.0
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install packages
        run: npm ci --ignore-scripts --allow-git=none

      - name: Create release pull request or publish to npm
        id: changesets
        uses: changesets/action@001cd79f0a536e733315164543a727bdf2d70aff # 001cd = v1.5.1
        with:
          cwd: packages/mint-components
          version: npm run version
          publish: npm run release
          title: "mint-components - Version Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

  deploy-docs:
    needs: publish
    runs-on: ubuntu-latest
    name: Deploy Docs

    permissions:
      contents: read
      id-token: write # GCP workload identity federation

    defaults:
      run:
        working-directory: packages/mint-components

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # de0fa = v6.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 53b83 = v6.3.0
        with:
          node-version: 24

      - name: Install packages
        run: npm ci --ignore-scripts --allow-git=none

      - name: Build docs site
        run: NODE_ENV=dev npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # 7c6bc = v3
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/167728399658/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "github-static-site-actions@static-site-proxy.iam.gserviceaccount.com"

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # aa548 = v3.0.1

      - name: Deploy docs to bucket
        run: gsutil -m rsync -d -r www/ gs://stencilbook_static_saasquatch/mint-components/production/
